app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import EmailForgetPasswordForm

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('category/', views.shop_category, name='category'),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register, name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='pages/password_reset_form.html',
        form_class=EmailForgetPasswordForm,
        email_template_name='pages/password_reset_email.html',
        subject_template_name='pages/password_reset_subject.html'
    ), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='pages/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='pages/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('password_reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='pages/password_reset_complete.html'
    ), name='password_reset_complete'),
]

winter_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('app.api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control input-lg',
        'name': 'firstname',
        'placeholder': 'Họ',
        'autofocus': 'autofocus'
    }))
    last_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control input-lg',
        'name': 'lastname',
        'placeholder': 'Tên'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control input-lg',
        'name': 'username',
        'placeholder': 'Username',
        'required': 'required'
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'email',
        'class': 'form-control input-lg',
        'name': 'email',
        'placeholder': 'Email',
        'required': 'required'
    }))
    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'password',
        'class': 'form-control input-lg',
        'name': 'password',
        'placeholder': 'Mật khẩu',
        'required': 'required'
    }))
    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'password',
        'class': 'form-control input-lg',
        'name': 'comfirm_password',
        'placeholder': 'Mật khẩu xác nhận',
        'required': 'required'
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError(
                "Tên tài khoản trên đã tồn tại"
            )
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                "Email trên đã tồn tại"
            )
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError(
                "Mật khẩu không khớp"
            )
        return password2


class EmailForgetPasswordForm(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email).exists():
            raise ValidationError(
                "Không tìm thấy địa chỉ email"
            )
        return email

app/templates/pages/category.html
{% extends 'index.html' %}
{% load static %}
{% block css %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}
{% block content %}
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        {% ifequal request.get_full_path '/category/' %}
                            <div class="breadcrumb_iner_item">
                                <p>Home / Category</p>
                            </div>
                        {% endifequal %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================Category Product Area =================-->
    <section class="cat_product_area section_padding border_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="left_sidebar_area">
                        <aside class="left_widgets p_filter_widgets sidebar_box_shadow">
                            <div class="l_w_title">
                                <h3>Categories</h3>
                            </div>
                            <div class="widgets_inner">
                                <ul class="list">
                                    {% for category in categories %}
                                        <li>
                                            <a href="#Electronics">{{ category }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </aside>

                        <aside class="left_widgets p_filter_widgets sidebar_box_shadow">
                            <div class="l_w_title">
                                <h3>filters</h3>
                            </div>
                            <div class="widgets_inner">
                                <ul class="list">
                                    <li>
                                        <input type="radio" aria-label="Radio button for following text input">
                                        <a href="#">Low to high</a>
                                    </li>
                                    <li>
                                        <input type="radio" aria-label="Radio button for following text input">
                                        <a href="#">High to low</a>
                                    </li>
                                    <li class="active">
                                        <input type="radio" aria-label="Radio button for following text input">
                                        <a href="#">Newest</a>
                                    </li>
                                </ul>
                            </div>
                        </aside>

                        <aside class="left_widgets p_filter_widgets price_rangs_aside sidebar_box_shadow">
                            <div class="l_w_title">
                                <h3>Price Filter</h3>
                            </div>
                            <div class="widgets_inner">
                                <div class="range_item">
                                    <div class="slider-wrap">
                                        <p class="slider-title">a price range</p>
                                        <div style="display: flex; align-items: center; justify-content: space-between">
                                            <input type="text">
                                            <span style="width: 7px; height: 1px; display: inline-block; margin: 0 4px 5px; vertical-align: middle; background: #9a9a9a; font-size: 0">-</span>
                                            <input type="text">
                                        </div>
                                        <button type="button" class="btn btn-default btn-block">OK</button>
                                    </div>
                                </div>
                            </div>
                        </aside>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product_top_bar d-flex justify-content-between align-items-center">
                                <div class="single_product_menu product_bar_item">
                                    <h2>Womans (12)</h2>
                                </div>
                                <div class="product_top_bar_iner product_bar_item d-flex">
                                    <div class="product_bar_single">
                                        <select class="wide">
                                            <option data-display="Default sorting">Default sorting</option>
                                            <option value="1">Some option</option>
                                            <option value="2">Another option</option>
                                            <option value="3">Potato</option>
                                        </select>
                                    </div>
                                    <div class="product_bar_single">
                                        <select>
                                            <option data-display="Show 12">Show 12</option>
                                            <option value="1">Show 20</option>
                                            <option value="2">Show 30</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% for product in contents.products %}
                            <div class="col-lg-4 col-sm-6">
                                <div class="single_category_product">
                                    <div class="single_category_img">
                                        <img src="{{ product.image }}" alt="">
                                        <div class="category_social_icon">
                                            <ul>
                                                <li><a href="#"><i class="ti-heart"></i></a></li>
                                                <li><a href="#"><i class="ti-bag"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="category_product_text">
                                            <a href="#"><h5>{{ product.name }}</h5></a>
                                            <p>${{ product.price }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-lg-12 text-center">
                            <a href="#" class="btn_2">More Items</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Category Product Area =================-->
    <!-- free shipping here -->
    <section class="shipping_details section_padding border_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_shopping_details">
                        <img src="{% static 'img/icon/icon_1.png' %}" alt="">
                        <h4>Free shipping</h4>
                        <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_shopping_details">
                        <img src="{% static 'img/icon/icon_2.png' %}" alt="">
                        <h4>Free shipping</h4>
                        <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_shopping_details">
                        <img src="{% static 'img/icon/icon_3.png' %}" alt="">
                        <h4>Free shipping</h4>
                        <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_shopping_details">
                        <img src="{% static 'img/icon/icon_4.png' %}" alt="">
                        <h4>Free shipping</h4>
                        <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- free shipping end -->
{% endblock %}

app/templates/pages/login.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    <title>Login to Winter Shop</title>
{% endblock %}
{% block css %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <body class="bg-white">
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
    <!--================Home Banner Area =================-->
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            {% ifequal request.get_full_path '/login/' %}
                                <p>Home / Login</p>
                            {% endifequal %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================login_part Area =================-->
    <section class="login_part section_padding">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_text text-center">
                        <div class="login_part_text_iner">
                            <h2>New to our Shop?</h2>
                            <p>There are advances being made in science and technology
                                everyday, and a good example of this is the</p>
                            <a href="{% url 'register' %}" class="btn_3">Create an Account</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>Welcome Back ! <br>
                                Please Sign in now</h3>
                            <form class="row contact_form" action="{% url 'login' %}" method="post"
                                  novalidate="novalidate">
                                {% csrf_token %}
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="username" name="username" value=""
                                           placeholder="Username or Email">
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control" id="password" name="password" value=""
                                           placeholder="Password">
                                </div>
                                <div class="col-md-12 form-group">
                                    {% if messages %}
                                        <ul class="messages">
                                            {% for message in messages %}
                                                {% ifequal message.tags 'error' %}
                                                    <div style="color: red">
                                                    <i class="fa fa-times" style="color: red"></i>
                                                        <strong>{{ message }}</strong>
                                                    </div>
                                                {% endifequal %}
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    <div class="creat_account d-flex align-items-center">
                                        <input type="checkbox" id="f-option" name="selector">
                                        <label for="f-option">Remember me</label>
                                    </div>
                                    <button type="submit" value="submit" class="btn_3">
                                        log in
                                    </button>
                                    <a class="lost_pass" href="{% url 'password_reset' %}">forget password?</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->

    <!-- subscribe_area part start-->
    <section class="instagram_photo">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="instagram_photo_iner">
                        <div class="single_instgram_photo">
                            <img src="{% static 'img/instagram/inst_1.png' %}" alt="">
                            <a href="#"><i class="ti-instagram"></i></a>
                        </div>
                        <div class="single_instgram_photo">
                            <img src="{% static 'img/instagram/inst_2.png' %}" alt="">
                            <a href="#"><i class="ti-instagram"></i></a>
                        </div>
                        <div class="single_instgram_photo">
                            <img src="{% static 'img/instagram/inst_3.png' %}" alt="">
                            <a href="#"><i class="ti-instagram"></i></a>
                        </div>
                        <div class="single_instgram_photo">
                            <img src="{% static 'img/instagram/inst_4.png' %}" alt="">
                            <a href="#"><i class="ti-instagram"></i></a>
                        </div>
                        <div class="single_instgram_photo">
                            <img src="{% static 'img/instagram/inst_5.png' %}" alt="">
                            <a href="#"><i class="ti-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--::subscribe_area part end::-->
    </body>
{% endblock %}

app/templates/pages/password_reset_complete.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    <title>Đặt lại mật khẩu</title>
{% endblock %}
{% block css %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <body>
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
    <form method='POST'>
        {% csrf_token %}
        <div class="row justify-content-center align-items-center ">
            <div class="col-lg-6 ">
                <div class="container card mt-5 mb-5" style="background-color: #f8f8f8;">
                    </br>
                    <h4>Quên mật khẩu</h4>
                    <hr/>
                    <div class="row border-primary d-flex justify-content-center align-items-center ">
                        <div class="col-lg-8 row">
                            <div class="col-lg-12">
                                <div class="form-group text-center">
                                    <label for=""><h5>Bạn đã đổi mật khẩu thành công.Bạn có thể đăng nhâp tài khoản bằng
                                        mật khẩu mới. </h5></label>
                                </div>
                                <div class="col-lg-12 mt-2 mb-5 d-flex justify-content-center">
                                    <a href="{% url 'login' %}" class=" btn btn-success ">Về lại trang đăng nhập</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </body>
{% endblock %}

app/templates/pages/password_reset_email.html
{% autoescape off %}
    Để đặt lại mật khẩu cho tài khoản {{ user.username }},
    vui lòng click vào link bên dưới:

    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}

    Nếu đường dẫn không hoạt động vui lòng thực hiện lại,
    Winter Shop
{% endautoescape %}

app/templates/pages/password_reset_subject.html
Yêu cầu đặt lại mật khẩu

app/templates/pages/register.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    <title>Create an account</title>
{% endblock %}
{% block css %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}
{% block content %}
    <body>
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
    <div class="signup-form">
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <h2>Create an account</h2>
            <p class="hint-text">Sign up with your social media account or email address</p>
            <div class="social-btn text-center">
                <a href="#" class="btn btn-primary btn-lg"><i class="fa fa-facebook"></i> Facebook</a>
                <a href="#" class="btn btn-info btn-lg"><i class="fa fa-twitter"></i> Twitter</a>
                <a href="#" class="btn btn-danger btn-lg"><i class="fa fa-google"></i> Google</a>
            </div>
            <div class="or-seperator"><b>or</b></div>
            <div class="form-group">
                {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password1 }}
            </div>
            <div class="form-group">
                {{ form.password2 }}
            </div>
            {% if form.errors %}
                <ul style="text-decoration: none">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li style="text-decoration: none;">
                                <strong style="color: red; font-size: 12px; font-style: italic">{{ error|escape }}</strong>
                            </li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-lg btn-block signup-btn">Tạo tài khoản</button>
            </div>
        </form>
        <div class="text-center">Đã có tài khoản? <a href="{% url 'login' %}">Đăng nhập</a></div>
    </div>
    </body>
{% endblock %}
{% block javascript %}
    <!-- jquery plugins here-->
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'font-awesome/js/fontawesome.min.js' %}"></script>
    <script type="javascript">
        $(document).ready(function () {
            window.onload = function () {
                $("#id_first_name").focus();
            }
        })
    </script>
{% endblock %}